M48
; DRILL file {KiCad (7.0.0-rc1-358-g86c12d35b4)} date Thursday, May 18, 2023 at 09:24:31 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-18T21:24:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-rc1-358-g86c12d35b4)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
%
G90
G05
T1
X108.446Y-110.388
X111.557Y-113.499
T0
M30
